theme: minima
title: liaozk`s world
description: one`s internal mediocrity is the moment when you lost the faith of being excellent.  
description: When you get the feeling that your work is OK, you have got killed another you who can make it much better.  
description: 去生活 去犯错 去跌倒 去胜利 去用生命再创生命


